NAME=test
SRCS=test.cpp 
LOCAL_CONFIG = -legup-config=config.tcl

LEVEL=$(LEGUP_EXAMPLES)
include $(LEVEL)/Makefile.common

EXTRA_SW_COMPILATION_FLAG = -I/usr/local/systemc-2.3.3/include -L/usr/local/systemc-2.3.3/lib/ -lsystemc -Wl,-rpath=/usr/local/systemc-2.3.3/lib/

